# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codegen.fullname" . }}
  labels:
    {{- include "codegen.labels" . | nindent 4 }}
    app: {{ include "codegen.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "codegen.selectorLabels" . | nindent 6 }}
      app: {{ include "codegen.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codegen.selectorLabels" . | nindent 8 }}
        app: {{ include "codegen.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "codegen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            # Use global LLM server host IP if provided, otherwise use default LLM service
            - name: LLM_SERVICE_HOST_IP
              {{- if .Values.global.LLM_SERVER_HOST_IP }}
              value: {{ .Values.global.LLM_SERVER_HOST_IP }}
              {{- else }}
              value: {{ .Release.Name }}-llm-uservice
              {{- end }}
            - name: LLM_SERVICE_PORT
              value: "80"
            {{- if .Values.global.LLM_MODEL }}
            - name: LLM_MODEL
              value: {{ .Values.global.LLM_MODEL | quote }}
            {{- end }}
            {{- if include "codegen.isOpenAIKeySet" . }}
            - name: OPENAI_API_KEY
              value: {{ include "codegen.getOpenAIKey" . | quote }}
            {{- end }}
            #- name: MEGA_SERVICE_PORT
            #  value: {{ .Values.port }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - name: codegen
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.evenly_distributed }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "codegen.selectorLabels" . | nindent 14 }}
              app: {{ include "codegen.fullname" . }}
      {{- end }}
