# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-central-gateway.fullname" . }}
  labels:
    {{- include "nginx-central-gateway.labels" . | nindent 4 }}
spec:
  {{- if ne (int .Values.replicaCount) 1 }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-central-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-central-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              envsubst '${FRONTEND_SERVICE_IP} ${FRONTEND_SERVICE_PORT} ${CHATQNA_SERVICE_IP} ${CHATQNA_SERVICE_PORT} ${CODEGEN_SERVICE_IP} ${CODEGEN_SERVICE_PORT} ${DOCSUM_SERVICE_IP} ${DOCSUM_SERVICE_PORT} ${DATAPREP_SERVICE_IP} ${DATAPREP_SERVICE_PORT} ${CHATHISTORY_SERVICE_IP} ${CHATHISTORY_SERVICE_PORT} ${PROMPT_SERVICE_IP} ${PROMPT_SERVICE_PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
              nginx -g 'daemon off;'
          envFrom:
            - configMapRef:
                name: {{ include "nginx-central-gateway.fullname" . }}-config
          ports:
            - name: nginx-gateway
              containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/templates/
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "nginx-central-gateway.fullname" . }}-config
            items:
              - key: default.conf.template
                path: default.conf.template
