# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    {{- include "chatqna.labels" . | nindent 4 }}
data:
  # Handle UI reference with hardcoded defaults for maximum compatibility
  FRONTEND_SERVICE_IP: {{ .Release.Name }}-chatqna-ui
  FRONTEND_SERVICE_PORT: "80"
  BACKEND_SERVICE_NAME: chatqna
  BACKEND_SERVICE_IP: {{ include "chatqna.fullname" . | quote }}
  BACKEND_SERVICE_PORT: {{ .Values.service.port | default "8888" | quote }}
  # Handle data-prep reference with hardcoded defaults
  DATAPREP_SERVICE_IP: {{ .Release.Name }}-data-prep
  DATAPREP_SERVICE_PORT: "8000"
